name: Update Changelog and Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # this is to make sure we have the full git history to generate the changelog

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # or the version of your choice

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Run script
        run: python changelog_and_version.py  # or the path to your script

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md version.txt
          git commit -m "Update changelog and version [skip ci]" || exit 0  # if there are no changes to commit, the exit code 0 avoids failing the workflow
          git push
      # create release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # this token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.version.outputs.version }}  # reference to the version output from the script run
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Changes in this Release
            - ${{ steps.version.outputs.changes }}  # assumes your script outputs a variable named changes
          draft: false
          prerelease: false